//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkExcercise
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductPurchase
    {
        public int id { get; set; }
        public string purchase_id { get; set; }
        public string product_id { get; set; }
        public string quantity { get; set; }
    }
}
