//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkExcercise
{
    using System;
    using System.Collections.Generic;
    
    public partial class RetailPurchase
    {
        public int id { get; set; }
        public int channel_code { get; set; }
        public string customer_id { get; set; }
        public string payment_id { get; set; }
        public string staff_id { get; set; }
        public string store_id { get; set; }
        public Nullable<System.DateTime> date_of_purchase { get; set; }
        public string amount { get; set; }
        public string description { get; set; }
    }
}
